# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  host: 127.0.0.1
  #host: '/Applications/MAMP/tmp/mysql/mysql.sock',
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  port: 7001
  socket: '/var/lib/mysql/mysql.sock'
  username: root
  password: password

development:
  <<: *default
  database: blog_develop


